services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./ssl-register-nginx/nginx.conf:/etc/nginx/nginx.conf
      - certs-data:/data/letsencrypt
    ports:
      - "80:80"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    depends_on:
      - nginx
volumes:
    certs: 
    certs-data: 
